{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 练习: 修正有效性"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "http://dbpedia.org/ontology/productionStartYear\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3066, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 65, in <module>\n",
      "    test()\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 61, in test\n",
      "    process_file(INPUT_FILE, OUTPUT_GOOD, OUTPUT_BAD)\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 33, in process_file\n",
      "    dt = datetime.strptime(datestring, '%Y-%m-%d %H:%M:%S')\n",
      "  File \"/usr/lib/python3.4/_strptime.py\", line 500, in _strptime_datetime\n",
      "    tt, fraction = _strptime(data_string, format)\n",
      "  File \"/usr/lib/python3.4/_strptime.py\", line 337, in _strptime\n",
      "    (data_string, format))\n",
      "ValueError: time data 'http://dbpedia.org/ontology/productionStartYear' does not match format '%Y-%m-%d %H:%M:%S'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 1338, in getinnerframes\n",
      "    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 1298, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 583, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 612, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 596, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/ds/lib/python3.4/posixpath.py\", line 361, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3066, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 65, in <module>\n",
      "    test()\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 61, in test\n",
      "    process_file(INPUT_FILE, OUTPUT_GOOD, OUTPUT_BAD)\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 33, in process_file\n",
      "    dt = datetime.strptime(datestring, '%Y-%m-%d %H:%M:%S')\n",
      "  File \"/usr/lib/python3.4/_strptime.py\", line 500, in _strptime_datetime\n",
      "    tt, fraction = _strptime(data_string, format)\n",
      "  File \"/usr/lib/python3.4/_strptime.py\", line 337, in _strptime\n",
      "    (data_string, format))\n",
      "ValueError: time data 'http://dbpedia.org/ontology/productionStartYear' does not match format '%Y-%m-%d %H:%M:%S'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3006, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3083, in run_code\n",
      "    self.showtraceback()\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1880, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1242, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1002, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 951, in format_exception_as_a_whole\n",
      "    frames = self.format_records(records)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 724, in format_records\n",
      "    for frame, file, lnum, func, lines, index in records:\n",
      "TypeError: 'NoneType' object is not iterable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 1338, in getinnerframes\n",
      "    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 1298, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 583, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 612, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/usr/lib/python3.4/inspect.py\", line 596, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/ds/lib/python3.4/posixpath.py\", line 361, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n",
      "ERROR: Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "'NoneType' object is not iterable",
     "output_type": "error",
     "traceback": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3066, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 65, in <module>\n    test()\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 61, in test\n    process_file(INPUT_FILE, OUTPUT_GOOD, OUTPUT_BAD)\n",
      "  File \"<ipython-input-8-5026aa481104>\", line 33, in process_file\n    dt = datetime.strptime(datestring, '%Y-%m-%d %H:%M:%S')\n",
      "  File \"/usr/lib/python3.4/_strptime.py\", line 500, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n",
      "  File \"/usr/lib/python3.4/_strptime.py\", line 337, in _strptime\n    (data_string, format))\n",
      "ValueError: time data 'http://dbpedia.org/ontology/productionStartYear' does not match format '%Y-%m-%d %H:%M:%S'\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3006, in run_ast_nodes\n    if self.run_code(code, result):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3083, in run_code\n    self.showtraceback()\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1880, in showtraceback\n    value, tb, tb_offset=tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1242, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1002, in structured_traceback\n    tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 951, in format_exception_as_a_whole\n    frames = self.format_records(records)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 724, in format_records\n    for frame, file, lnum, func, lines, index in records:\n",
      "TypeError: 'NoneType' object is not iterable\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/ipykernel/ipkernel.py\", line 175, in do_execute\n    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 2902, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3031, in run_ast_nodes\n    self.showtraceback()\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1880, in showtraceback\n    value, tb, tb_offset=tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1242, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1020, in structured_traceback\n    chained_exceptions_tb_offset)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 951, in format_exception_as_a_whole\n    frames = self.format_records(records)\n",
      "  File \"/opt/ds/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 724, in format_records\n    for frame, file, lnum, func, lines, index in records:\n",
      "TypeError: 'NoneType' object is not iterable\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 3\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "你的任务是检查 DBPedia 自动数据文件的“productionStartYear”并获取有效的值。应该完成以下任务：\n",
    "-    检查字段“productionStartYear”是否包含年份\n",
    "-    检查该年份是否在 1886 至 2014 范围内\n",
    "-    将字段值转换为年份（而不是整个日期时间）\n",
    "-    字段的其他部分和值应该保持不变\n",
    "-    如果字段的值是如上所述范围内的有效年份，则将该行写入 output_good 文件中\n",
    "-    如果字段的值不是如上所述的有效年份，则将该行写入 output_bad 文件中\n",
    "-    你应该采用提供的数据读取和写入方式（DictReader 和 DictWriter），它们将会对标题进行处理。\n",
    "\n",
    "你可以编写辅助函数来检查数据并编写文件，但是我们将仅调用包含三个参数（inputfile、output_good、output_bad）的“process_file”文件。\n",
    "\"\"\"\n",
    "import csv\n",
    "import pprint\n",
    "from datetime import datetime\n",
    "\n",
    "INPUT_FILE = 'autos.csv'\n",
    "OUTPUT_GOOD = 'autos-valid.csv'\n",
    "OUTPUT_BAD = 'FIXME-autos.csv'\n",
    "\n",
    "def process_file(input_file, output_good, output_bad):\n",
    "\n",
    "    with open(input_file, \"r\") as f:\n",
    "        reader = csv.DictReader(f)\n",
    "        header = reader.fieldnames\n",
    "        \n",
    "        good_data = []\n",
    "        bad_data = []\n",
    "        \n",
    "        for row in reader:\n",
    "            datestring = row[\"productionStartYear\"]\n",
    "            print(datestring)\n",
    "            dt = datetime.strptime(datestring, '%Y-%m-%d %H:%M:%S')\n",
    "            print(dt.year)\n",
    "            try:\n",
    "                dt = datetime.datetime.strptime(datestring, '%Y-%m-%d %H:%M:%S')\n",
    "                # if (dt.year >= 1886) and (dt.year <= 2014):\n",
    "                    #good_data.append(row)\n",
    "                #else:\n",
    "                    #bad_data.append(row)\n",
    "            except Exception: \n",
    "                bad_data.append(row)\n",
    "\n",
    "    # This is just an example on how you can use csv.DictWriter\n",
    "    # Remember that you have to output 2 files\n",
    "    with open(output_good, \"w\") as g:\n",
    "        writer = csv.DictWriter(g, delimiter=\",\", fieldnames= header)\n",
    "        writer.writeheader()\n",
    "        for row in good_data:\n",
    "            writer.writerow(row)\n",
    "            \n",
    "    with open(output_bad, \"w\") as g:\n",
    "        writer = csv.DictWriter(g, delimiter=\",\", fieldnames= header)\n",
    "        writer.writeheader()\n",
    "        for row in bad_data:\n",
    "            writer.writerow(row)\n",
    "\n",
    "\n",
    "def test():\n",
    "\n",
    "    process_file(INPUT_FILE, OUTPUT_GOOD, OUTPUT_BAD)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    test()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
